sudo: required

services:
  - docker

# Definir las ramas a construir.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Definir las ambientes de construcción.
stages:
  - build
  - test
  - deploy

# Definir los trabajos para cada ambiente.
jobs:
  include:
    - stage: build
      before_install:
        - docker build -t stackovernani10/inventory-management-software -f Dockerfile.dev .
      script:
        - docker run stackovernani10/inventory-management-software npm run build
        - bundle exec rake build
      # Notificamos que a pasado el ambiente build al encargado del mismo
      notifications:
        email:
          recipients:
            - 1097711@est.intec.edu.do
          on_success: always
          on_failure: always

    - stage: test
      name: "Unit Tests"
      script:
        - npm run test
      #name: "Integration Tests"
      #script:
      #  - ./integration-tests
      # Notificamos que a pasado el ambiente test al encargado del mismo
      notifications:
        email:
          recipients:
            - 1106095@est.intec.edu.do
          on_success: always
          on_failure: always

     - stage: deploy
      script:
        - bundle exec rake deploy
      if: branch = master AND type = push
      provider: releases # use Github pages instead: pages
      token: $GITHUB_TOKEN
      file_glob: true
      file: ./
      skip_cleanup: true
      overwrite: true
      on:
        branch: master
      # Notificamos que a pasado el ambiente deploy al encargado del mismo
      notifications:
        email:
          recipients:
            - 1106630@est.intec.edu.do
          on_success: always
          on_failure: always
